package com.ExceptionHandling;

public class Example_137 {
	public static void main(String[] args) {
		System.out.println(1.1);
//		try {
//			System.out.println("2");
//			System.out.println("3");
//			System.out.println(4);
//		}
//		catch(ArithmeticException  e){
//			System.out.println("5");
//			System.out.println("6");
//		}
//		System.out.println("8");
//	}
		
	//	try {}
	//	int a=9;
	//	catch(Exception e) {}
	//	int b=8;
	//	finally {}
	//	catch(Exception e) {}
	}	
}
